// vehicules-data.js
const VEHICLES_DATA = [
    // === Compact ===
    { type:"Compact", marque:"Benefactor", modele:"Panto", prix:"$3 200,00" },
    { type:"Compact", marque:"Maxwell", modele:"Abso", prix:"$4 000,00" },
    { type:"Compact", marque:"Weeny", modele:"Issi Classic", prix:"$5 000,00" },
    { type:"Compact", marque:"BF", modele:"Club", prix:"$8 000,00" },
    { type:"Compact", marque:"Karin", modele:"Dilettante", prix:"$9 000,00" },
    { type:"Compact", marque:"BF", modele:"Weevil", prix:"$9 000,00" },
    { type:"Compact", marque:"Weeny", modele:"Issi", prix:"$9 100,00" },
    { type:"Compact", marque:"Declasse", modele:"Rhapsody", prix:"$10 000,00" },
    { type:"Compact", marque:"Grotti", modele:"Brioso 300", prix:"$12 000,00" },
    { type:"Compact", marque:"Dinka", modele:"Blista Kanjo", prix:"$12 000,00" },
    { type:"Compact", marque:"Dinka", modele:"Blista", prix:"$13 000,00" },
    { type:"Compact", marque:"Dinka", modele:"Blista Compact", prix:"$18 950,00" },
    { type:"Compact", marque:"Grotti", modele:"Brioso R/A", prix:"$20 000,00" },
    { type:"Compact", marque:"Dinka", modele:"Blista Go Go Monkey", prix:"$22 000,00" },
    { type:"Compact", marque:"Karin", modele:"Boor", prix:"$23 000,00" },
    { type:"Compact", marque:"Bollokan", modele:"Prairie", prix:"$30 000,00" },
    { type:"Compact", marque:"Grotti", modele:"Brioso Fulmin", prix:"$30 000,00" },
    { type:"Compact", marque:"Bordeaux", modele:"Vivant", prix:"$40 000,00" },
    { type:"Compact", marque:"Weeny", modele:"Issi Sport", prix:"$60 000,00" },
    { type:"Compact", marque:"Grotti", modele:"Brioso 300 Widebody", prix:"$70 000,00" },
    { type:"Compact", marque:"Bollokan", modele:"Iris Z", prix:"$85 000,00" },
    { type:"Compact", marque:"BF", modele:"Club XR", prix:"$88 000,00" },

    // === Sedans ===
    { type:"Sedans", marque:"Dundreary", modele:"Regina", prix:"$7 000,00" },
    { type:"Sedans", marque:"Vulcar", modele:"Ingot", prix:"$8 000,00" },
    { type:"Sedans", marque:"Declasse", modele:"Asea", prix:"$8 000,00" },
    { type:"Sedans", marque:"Benefactor", modele:"Glendale", prix:"$8 200,00" },
    { type:"Sedans", marque:"Vulcar", modele:"Warrener", prix:"$8 600,00" },
    { type:"Sedans", marque:"Albany", modele:"Emperor", prix:"$10 000,00" },
    { type:"Sedans", marque:"Karin", modele:"Asterope", prix:"$11 000,00" },
    { type:"Sedans", marque:"Albany", modele:"Primo", prix:"$11 000,00" },
    { type:"Sedans", marque:"Karin", modele:"Intruder", prix:"$11 250,00" },
    { type:"Sedans", marque:"Albany", modele:"Washington", prix:"$12 000,00" },
    { type:"Sedans", marque:"Benefactor", modele:"Glendale Custom", prix:"$12 000,00" },
    { type:"Sedans", marque:"Declasse", modele:"Premier", prix:"$12 000,00" },
    { type:"Sedans", marque:"Declasse", modele:"Impaler", prix:"$13 000,00" },
    { type:"Sedans", marque:"Albany", modele:"Primo Custom", prix:"$14 500,00" },
    { type:"Sedans", marque:"Zirconium", modele:"Stratum", prix:"$15 000,00" },
    { type:"Sedans", marque:"Dundreary", modele:"Hades", prix:"$16 000,00" },
    { type:"Sedans", marque:"Benefactor", modele:"Schafter", prix:"$16 000,00" },
    { type:"Sedans", marque:"Enus", modele:"Super Diamond", prix:"$17 000,00" },
    { type:"Sedans", marque:"Willard", modele:"Eudora", prix:"$17 000,00" },
    { type:"Sedans", marque:"Dundreary", modele:"Admiral", prix:"$18 000,00" },
    { type:"Sedans", marque:"Vapid", modele:"Stanier", prix:"$19 000,00" },
    { type:"Sedans", marque:"Cheval", modele:"Fugitive", prix:"$20 000,00" },
    { type:"Sedans", marque:"Cheval", modele:"Surge", prix:"$20 000,00" },
    { type:"Sedans", marque:"Karin", modele:"Asterope GZ", prix:"$21 000,00" },
    { type:"Sedans", marque:"Übermacht", modele:"Oracle", prix:"$22 000,00" },
    { type:"Sedans", marque:"Obey", modele:"Tailgater", prix:"$22 000,00" },
    { type:"Sedans", marque:"Enus", modele:"Cognoscenti 55", prix:"$22 000,00" },
    { type:"Sedans", marque:"Enus", modele:"Cognoscenti", prix:"$22 500,00" },
    { type:"Sedans", marque:"Benefactor", modele:"Schrauber", prix:"$25 000,00" },
    { type:"Sedans", marque:"Vulcar", modele:"Warrener HKR", prix:"$30 000,00" },
    { type:"Sedans", marque:"Declasse", modele:"Tahoma GT", prix:"$32 000,00" },
    { type:"Sedans", marque:"Vulcan", modele:"Starlight", prix:"$45 000,00" },
    { type:"Sedans", marque:"Obey", modele:"Tailgater S", prix:"$51 000,00" },
    { type:"Sedans", marque:"Enus", modele:"Stafford", prix:"$80 000,00" },
    { type:"Sedans", marque:"Übermacht", modele:"Rhinehart", prix:"$105 000,00" },
    { type:"Sedans", marque:"Lampadati", modele:"Cinquemila", prix:"$125 000,00" },
    { type:"Sedans", marque:"Pfister", modele:"S2 Cabriolet Comet", prix:"$140 000,00" },
    { type:"Sedans", marque:"Gallivanter", modele:"Baller ST", prix:"$145 000,00" },
    { type:"Sedans", marque:"Pfister", modele:"Astron", prix:"$150 000,00" },
    { type:"Sedans", marque:"Enus", modele:"Sapphire", prix:"$180 000,00" },
    { type:"Sedans", marque:"Obey", modele:"I-Wagen", prix:"$225 000,00" },
    { type:"Sedans", marque:"Enus", modele:"Deity", prix:"$320 000,00" },
    { type:"Sedans", marque:"Enus", modele:"Jubilee", prix:"$350 000,00" },
    { type:"Sedans", marque:"Dundreary", modele:"Stretch", prix:"$550 000,00" },

    // === SUVs ===
    { type:"SUVs", marque:"Karin", modele:"Beejay XL", prix:"$19 000,00" },
    { type:"SUVs", marque:"Dundreary", modele:"Landstalker", prix:"$20 000,00" },
    { type:"SUVs", marque:"Emperor", modele:"Habanero", prix:"$20 000,00" },
    { type:"SUVs", marque:"Canis", modele:"Seminole", prix:"$20 000,00" },
    { type:"SUVs", marque:"Canis", modele:"Seminole Frontier", prix:"$21 000,00" },
    { type:"SUVs", marque:"Albany", modele:"Cavalcade", prix:"$21 000,00" },
    { type:"SUVs", marque:"Vapid", modele:"Radius", prix:"$23 000,00" },
    { type:"SUVs", marque:"Benefactor", modele:"XLS", prix:"$23 000,00" },
    { type:"SUVs", marque:"Bravado", modele:"Dorado", prix:"$24 000,00" },
    { type:"SUVs", marque:"Enus", modele:"Huntley S", prix:"$24 500,00" },
    { type:"SUVs", marque:"Obey", modele:"Rocoto", prix:"$25 000,00" },
    { type:"SUVs", marque:"Bravado", modele:"Gresley", prix:"$25 000,00" },
    { type:"SUVs", marque:"Albany", modele:"Cavalcade II", prix:"$25 000,00" },
    { type:"SUVs", marque:"Fathom", modele:"FQ2", prix:"$25 500,00" },
    { type:"SUVs", marque:"Dundreary", modele:"Landstalker XL", prix:"$26 000,00" },
    { type:"SUVs", marque:"Gallivanter", modele:"Baller", prix:"$27 000,00" },
    { type:"SUVs", marque:"Benefactor", modele:"Dubsta", prix:"$29 000,00" },
    { type:"SUVs", marque:"Benefactor", modele:"Serrano", prix:"$32 000,00" },
    { type:"SUVs", marque:"Benefactor", modele:"Dubsta Luxury", prix:"$33 000,00" },
    { type:"SUVs", marque:"Gallivanter", modele:"Baller II", prix:"$35 000,00" },
    { type:"SUVs", marque:"Vapid", modele:"Contender", prix:"$42 000,00" },
    { type:"SUVs", marque:"Gallivanter", modele:"Baller LE", prix:"$43 000,00" },
    { type:"SUVs", marque:"Declasse", modele:"Granger", prix:"$45 000,00" },
    { type:"SUVs", marque:"Vapid", modele:"Aleutian", prix:"$45 000,00" },
    { type:"SUVs", marque:"Declasse", modele:"Granger 3600LX", prix:"$47 000,00" },
    { type:"SUVs", marque:"Gallivanter", modele:"Baller LE LWB", prix:"$47 000,00" },
    { type:"SUVs", marque:"Gallivanter", modele:"Baller ST-D", prix:"$52 000,00" },
    { type:"SUVs", marque:"Lampadati", modele:"Novak", prix:"$60 000,00" },
    { type:"SUVs", marque:"Karin", modele:"Vivanite", prix:"$75 000,00" },
    { type:"SUVs", marque:"Übermacht", modele:"Rebla GTS", prix:"$100 000,00" },
    { type:"SUVs", marque:"Coil", modele:"LOD 4", prix:"$110 000,00" },
    { type:"SUVs", marque:"Albany", modele:"Cavalcade XL", prix:"$125 000,00" },
    { type:"SUVs", marque:"Bravado", modele:"Gresley STX", prix:"$140 000,00" },
    { type:"SUVs", marque:"Pegassi", modele:"Toros", prix:"$180 000,00" },
    { type:"SUVs", marque:"Mammoth", modele:"Patriot", prix:"$250 000,00" },
    { type:"SUVs", marque:"Mammoth", modele:"Patriot stretch", prix:"$310 000,00" },

    // … puis continue exactement de la même façon pour
    // Coupes, Muscle, Sport-Classics, Sport, Super, Motorcyles, Off-Roads, VAN
    // en recopiant toutes les lignes restantes du fichier. [file:82]
];
// Suite de VEHICLES_DATA

// === Coupes ===
VEHICLES_DATA.push(
    { type:"Coupes", marque:"Declasse", modele:"Tahoma coupe", prix:"$16 000,00" },
    { type:"Coupes", marque:"Karin", modele:"Futo", prix:"$17 500,00" },
    { type:"Coupes", marque:"Übermacht", modele:"Zion", prix:"$22 000,00" },
    { type:"Coupes", marque:"Dinka", modele:"Kanjo SJ", prix:"$24 000,00" },
    { type:"Coupes", marque:"Übermacth", modele:"Sentinel", prix:"$26 000,00" },
    { type:"Coupes", marque:"Übermacth", modele:"Sentinel XS", prix:"$28 000,00" },
    { type:"Coupes", marque:"Karin", modele:"Previon", prix:"$29 000,00" },
    { type:"Coupes", marque:"Enus", modele:"Cognoscenti Cabrio", prix:"$30 000,00" },
    { type:"Coupes", marque:"Fanthom", modele:"FR36", prix:"$32 000,00" },
    { type:"Coupes", marque:"Übermacth", modele:"Zion Cabrio", prix:"$32 000,00" },
    { type:"Coupes", marque:"Ocelot", modele:"Jackal", prix:"$34 000,00" },
    { type:"Coupes", marque:"Lampadati", modele:"Felon", prix:"$36 000,00" },
    { type:"Coupes", marque:"Lampadati", modele:"Felon GT", prix:"$45 000,00" },
    { type:"Coupes", marque:"Enus", modele:"Windsor Drop", prix:"$59 000,00" },
    { type:"Coupes", marque:"Dewbauchee", modele:"Exemplar", prix:"$62 000,00" },
    { type:"Coupes", marque:"Übermacth", modele:"Sentinel Classic", prix:"$70 000,00" },
    { type:"Coupes", marque:"Ocelot", modele:"F620", prix:"$72 000,00" },
    { type:"Coupes", marque:"Coil", modele:"Eon", prix:"$110 000,00" },
    { type:"Coupes", marque:"Übermacth", modele:"Sentinel G", prix:"$115 000,00" },
    { type:"Coupes", marque:"Classique", modele:"Broadway", prix:"$130 000,00" },
    { type:"Coupes", marque:"Dewbauchee", modele:"Champion", prix:"$360 000,00" }
);

// === Muscle ===
VEHICLES_DATA.push(
    { type:"Muscle", marque:"Vapid", modele:"Chino", prix:"$8 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Chino Luxe", prix:"$12 000,00" },
    { type:"Muscle", marque:"Albany", modele:"Manana", prix:"$12 800,00" },
    { type:"Muscle", marque:"Declasse", modele:"Voodoo", prix:"$13 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Clique Wagon", prix:"$15 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Slam Van", prix:"$16 000,00" },
    { type:"Muscle", marque:"Willard", modele:"Faction", prix:"$17 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Slam Van Custom", prix:"$17 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Greenwood", prix:"$18 000,00" },
    { type:"Muscle", marque:"Willard", modele:"Faction Rider", prix:"$19 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Yosemite", prix:"$19 500,00" },
    { type:"Muscle", marque:"Cheval", modele:"Picador", prix:"$20 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Clique", prix:"$20 000,00" },
    { type:"Muscle", marque:"Ratloader2", modele:"Ratloader", prix:"$20 000,00" },
    { type:"Muscle", marque:"Dundreary", modele:"Virgo", prix:"$21 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Lurcher", prix:"$21 000,00" },
    { type:"Muscle", marque:"Dundreary", modele:"Virgo Custom Classic", prix:"$21 000,00" },
    { type:"Muscle", marque:"Albany", modele:"Virgo", prix:"$22 000,00" },
    { type:"Muscle", marque:"Albany", modele:"Buccaneer", prix:"$22 500,00" },
    { type:"Muscle", marque:"Imponte", modele:"Dukes", prix:"$23 500,00" },
    { type:"Muscle", marque:"Vapid", modele:"Blade", prix:"$23 500,00" },
    { type:"Muscle", marque:"Albany", modele:"Manana Custom", prix:"$24 000,00" },
    { type:"Muscle", marque:"Albany", modele:"Buccaneer Rider", prix:"$24 500,00" },
    { type:"Muscle", marque:"Declasse", modele:"Impaler LX", prix:"$25 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Tulip M-100", prix:"$25 000,00" },
    { type:"Muscle", marque:"Imponte", modele:"Ruiner", prix:"$29 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Vamos", prix:"$30 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Stallion", prix:"$33 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Tampa", prix:"$34 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Gautlet", prix:"$34 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Classic Gaultet", prix:"$37 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Sabre GT Turbo", prix:"$37 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Impaler", prix:"$38 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Vigero", prix:"$39 500,00" },
    { type:"Muscle", marque:"Declasse", modele:"Drift Tampa", prix:"$40 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Stallion Burgershot", prix:"$40 000,00" },
    { type:"Muscle", marque:"Imponte", modele:"Ruiner ZZ-8", prix:"$41 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Sabre GT Turbo Custom", prix:"$42 000,00" },
    { type:"Muscle", marque:"Imponte", modele:"Phoenix", prix:"$42 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Ellie", prix:"$42 500,00" },
    { type:"Muscle", marque:"Vapid", modele:"Dominator", prix:"$45 000,00" },
    { type:"Muscle", marque:"Imponte", modele:"Beater Dukes", prix:"$45 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Gautlet Classic Custom", prix:"$46 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"PiBwasser", prix:"$50 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Yosemite Drift", prix:"$55 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Dominator ASP", prix:"$56 000,00" },
    { type:"Muscle", marque:"Schyster", modele:"Deviant", prix:"$70 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Redwood Gautlet", prix:"$70 000,00" },
    { type:"Muscle", marque:"Imponte", modele:"Nightshade", prix:"$70 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Dominator GTX", prix:"$75 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Dominator GTT", prix:"$80 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Gautlet Helfire", prix:"$80 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Tulip", prix:"$80 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Buffalo EVX", prix:"$86 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Hotknife", prix:"$90 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Hustler", prix:"$95 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Vigero ZX", prix:"$96 000,00" },
    { type:"Muscle", marque:"Bravado", modele:"Buffalo STX", prix:"$120 000,00" },
    { type:"Muscle", marque:"Albany", modele:"Brigham", prix:"$149 000,00" },
    { type:"Muscle", marque:"Vapid", modele:"Dominator GT", prix:"$174 000,00" },
    { type:"Muscle", marque:"Invetero", modele:"Coquette BlackFin", prix:"$180 000,00" },
    { type:"Muscle", marque:"Declasse", modele:"Vigero ZX Convertible", prix:"$181 000,00" },
    { type:"Muscle", marque:"Albany", modele:"Hermes", prix:"$199 000,00" }
);

// === Sport-Classics ===
VEHICLES_DATA.push(
    { type:"Sport-Classics", marque:"Rune", modele:"Cheburek", prix:"$7 000,00" },
    { type:"Sport-Classics", marque:"Vapid", modele:"Peyote", prix:"$12 000,00" },
    { type:"Sport-Classics", marque:"Vulcar", modele:"Fagaloa", prix:"$13 000,00" },
    { type:"Sport-Classics", marque:"Weeny", modele:"Dynasty", prix:"$13 500,00" },
    { type:"Sport-Classics", marque:"Vulcar", modele:"Nebula", prix:"$14 000,00" },
    { type:"Sport-Classics", marque:"Vapid", modele:"Retinue", prix:"$18 300,00" },
    { type:"Sport-Classics", marque:"Declasse", modele:"Tornado", prix:"$18 500,00" },
    { type:"Sport-Classics", marque:"Declasse", modele:"Tornado Custom", prix:"$19 000,00" },
    { type:"Sport-Classics", marque:"Declasse", modele:"Tornado Convertible", prix:"$21 000,00" },
    { type:"Sport-Classics", marque:"Lampadati", modele:"Michelli GT", prix:"$23 000,00" },
    { type:"Sport-Classics", marque:"Lampadati", modele:"Pigalle", prix:"$23 000,00" },
    { type:"Sport-Classics", marque:"Übermacht", modele:"Zion Classic", prix:"$23 000,00" },
    { type:"Sport-Classics", marque:"Lampadati", modele:"Komoda GT", prix:"$27 000,00" },
    { type:"Sport-Classics", marque:"Annis", modele:"Savestra", prix:"$31 000,00" },
    { type:"Sport-Classics", marque:"Maxwell", modele:"Sidewinder", prix:"$38 000,00" },
    { type:"Sport-Classics", marque:"Vapid", modele:"Peyote Gasser", prix:"$40 000,00" },
    { type:"Sport-Classics", marque:"Lampadati", modele:"Casco", prix:"$44 000,00" },
    { type:"Sport-Classics", marque:"Vapid", modele:"Peyote Custom", prix:"$48 000,00" },
    { type:"Sport-Classics", marque:"Dewbauchee", modele:"Rapid GT Classic", prix:"$65 000,00" },
    { type:"Sport-Classics", marque:"Tundra", modele:"Raidillon", prix:"$68 000,00" },
    { type:"Sport-Classics", marque:"Pfister", modele:"Comet Classic", prix:"$70 000,00" },
    { type:"Sport-Classics", marque:"Grotti", modele:"Stinger", prix:"$71 000,00" },
    { type:"Sport-Classics", marque:"Karin", modele:"190Z", prix:"$78 000,00" },
    { type:"Sport-Classics", marque:"Pegassi", modele:"Torero", prix:"$84 000,00" },
    { type:"Sport-Classics", marque:"Grotti", modele:"Stinger GT", prix:"$89 000,00" },
    { type:"Sport-Classics", marque:"Pegassi", modele:"Monroe", prix:"$115 000,00" },
    { type:"Sport-Classics", marque:"Benefactor", modele:"Stirling GT", prix:"$115 000,00" },
    { type:"Sport-Classics", marque:"Grotti", modele:"GT500", prix:"$130 000,00" },
    { type:"Sport-Classics", marque:"Declasse", modele:"Mamba", prix:"$140 000,00" },
    { type:"Sport-Classics", marque:"Invetero", modele:"Coquette Classic", prix:"$165 000,00" },
    { type:"Sport-Classics", marque:"Grotti", modele:"Turismo Classic", prix:"$170 000,00" },
    { type:"Sport-Classics", marque:"Albany", modele:"Roosevelt", prix:"$180 000,00" },
    { type:"Sport-Classics", marque:"Albany", modele:"Roosevelt Valor", prix:"$190 000,00" },
    { type:"Sport-Classics", marque:"Lampadati", modele:"Viseris", prix:"$210 000,00" },
    { type:"Sport-Classics", marque:"Ocelot", modele:"Swinger", prix:"$221 000,00" },
    { type:"Sport-Classics", marque:"Pegassi", modele:"Infernus Classic", prix:"$245 000,00" },
    { type:"Sport-Classics", marque:"Truffade", modele:"Z-Type", prix:"$270 000,00" }
);
// === Sport ===
VEHICLES_DATA.push(
    { type:"Sport", marque:"Maibastu", modele:"Penumbra", prix:"$22 000,00" },
    { type:"Sport", marque:"Karin", modele:"Futo GTX", prix:"$26 000,00" },
    { type:"Sport", marque:"Maibastu", modele:"Penumbra FF", prix:"$27 000,00" },
    { type:"Sport", marque:"Benefactor", modele:"Schwartzer", prix:"$27 000,00" },
    { type:"Sport", marque:"Bravado", modele:"Buffalo", prix:"$28 000,00" },
    { type:"Sport", marque:"Annis", modele:"ZR350", prix:"$31 000,00" },
    { type:"Sport", marque:"Annis", modele:"Remus", prix:"$31 500,00" },
    { type:"Sport", marque:"Bravado", modele:"Buffalo S", prix:"$33 000,00" },
    { type:"Sport", marque:"Benefactor", modele:"Schafter V12", prix:"$35 000,00" },
    { type:"Sport", marque:"Weeny", modele:"Issi Rally", prix:"$36 000,00" },
    { type:"Sport", marque:"Karin", modele:"Calico GTF", prix:"$36 000,00" },
    { type:"Sport", marque:"Dinka", modele:"RT3000", prix:"$39 000,00" },
    { type:"Sport", marque:"Vapid", modele:"Flash GT", prix:"$48 000,00" },
    { type:"Sport", marque:"Karin", modele:"Sultan", prix:"$50 000,00" },
    { type:"Sport", marque:"Albany", modele:"Alpha", prix:"$53 000,00" },
    { type:"Sport", marque:"Karin", modele:"Sultan Custom", prix:"$55 000,00" },
    { type:"Sport", marque:"Karin", modele:"Sultan Classic Custom", prix:"$56 000,00" },
    { type:"Sport", marque:"Lampadati", modele:"Komoda", prix:"$62 000,00" },
    { type:"Sport", marque:"Dinka", modele:"Sugoi", prix:"$62 000,00" },
    { type:"Sport", marque:"Lampadati", modele:"Tropos Rallye", prix:"$65 000,00" },
    { type:"Sport", marque:"Grotti", modele:"Bestia GTS", prix:"$67 000,00" },
    { type:"Sport", marque:"Wow", modele:"Omnis", prix:"$68 000,00" },
    { type:"Sport", marque:"Bravado", modele:"Verlierer", prix:"$68 000,00" },
    { type:"Sport", marque:"Toundra", modele:"Panthere", prix:"$69 000,00" },
    { type:"Sport", marque:"Vapid", modele:"GB 200", prix:"$71 000,00" },
    { type:"Sport", marque:"Karin", modele:"Kuruma", prix:"$72 000,00" },
    { type:"Sport", marque:"Annis", modele:"Elegy RH8", prix:"$72 000,00" },
    { type:"Sport", marque:"Annis", modele:"300R", prix:"$73 000,00" },
    { type:"Sport", marque:"Dinka", modele:"Jester Classic", prix:"$76 000,00" },
    { type:"Sport", marque:"Annis", modele:"Elegy Retro Custom", prix:"$76 000,00" },
    { type:"Sport", marque:"Karin", modele:"Sultan RS", prix:"$76 500,00" },
    { type:"Sport", marque:"Dewbauchee", modele:"Solace VI", prix:"$78 000,00" },
    { type:"Sport", marque:"Obey", modele:"Argento 7F", prix:"$80 000,00" },
    { type:"Sport", marque:"Dewbauchee", modele:"Rapid GT", prix:"$86 000,00" },
    { type:"Sport", marque:"Karin", modele:"Sultan RSX", prix:"$88 000,00" },
    { type:"Sport", marque:"Ocelot", modele:"Pariah", prix:"$90 000,00" },
    { type:"Sport", marque:"Hijak", modele:"Khamelion", prix:"$90 000,00" },
    { type:"Sport", marque:"Dewbauchee", modele:"Rapid GT Convertible", prix:"$92 000,00" },
    { type:"Sport", marque:"Benefactor", modele:"Feltzer", prix:"$97 000,00" },
    { type:"Sport", marque:"Bravado", modele:"Banshee", prix:"$106 000,00" },
    { type:"Sport", marque:"Dewbauchee", modele:"Massacro", prix:"$130 000,00" },
    { type:"Sport", marque:"Dinka", modele:"Jester", prix:"$132 250,00" },
    { type:"Sport", marque:"Benefactor", modele:"Surano", prix:"$135 000,00" },
    { type:"Sport", marque:"Överflöd", modele:"Imorgon", prix:"$135 000,00" },
    { type:"Sport", marque:"Enus", modele:"Paragon", prix:"$140 000,00" },
    { type:"Sport", marque:"Dewbauchee", modele:"Seven-70", prix:"$140 000,00" },
    { type:"Sport", marque:"Annis", modele:"Euros", prix:"$140 000,00" },
    { type:"Sport", marque:"Invetero", modele:"Coquette", prix:"$145 000,00" },
    { type:"Sport", marque:"Ocelot", modele:"Lynx", prix:"$150 000,00" },
    { type:"Sport", marque:"Dewbauchee", modele:"Massacro Racecar", prix:"$152 000,00" },
    { type:"Sport", marque:"Grotti", modele:"Carbonizzare", prix:"$155 000,00" },
    { type:"Sport", marque:"Albany", modele:"V-STR", prix:"$155 000,00" },
    { type:"Sport", marque:"Übermacht", modele:"Cypher", prix:"$155 000,00" },
    { type:"Sport", marque:"Obey", modele:"8F Drafter", prix:"$160 000,00" },
    { type:"Sport", marque:"Dewbauchee", modele:"Specter", prix:"$160 000,00" },
    { type:"Sport", marque:"Ocelot", modele:"Jugular", prix:"$165 000,00" },
    { type:"Sport", marque:"Emperor", modele:"Vectre", prix:"$174 000,00" },
    { type:"Sport", marque:"Dinka", modele:"Jester RR", prix:"$190 000,00" },
    { type:"Sport", marque:"Vapid", modele:"Dominator GSX", prix:"$195 000,00" },
    { type:"Sport", marque:"Grotti", modele:"Cheetah Classic", prix:"$195 000,00" },
    { type:"Sport", marque:"Obey", modele:"9F", prix:"$210 000,00" },
    { type:"Sport", marque:"Lampadati", modele:"Furore GT", prix:"$210 000,00" },
    { type:"Sport", marque:"Dinka", modele:"Jester Racecar", prix:"$210 000,00" },
    { type:"Sport", marque:"Obey", modele:"9F Cabrio", prix:"$225 000,00" },
    { type:"Sport", marque:"Vysser", modele:"Neo", prix:"$230 000,00" },
    { type:"Sport", marque:"Maibastu", modele:"Itali GTO Stinger TT", prix:"$238 000,00" },
    { type:"Sport", marque:"Obey", modele:"10F", prix:"$240 000,00" },
    { type:"Sport", marque:"Pfister", modele:"Neon", prix:"$240 000,00" },
    { type:"Sport", marque:"Obey", modele:"10F Widebody", prix:"$260 000,00" },
    { type:"Sport", marque:"Pfister", modele:"Growler", prix:"$265 000,00" },
    { type:"Sport", marque:"Pfister", modele:"Comet SR", prix:"$320 000,00" },
    { type:"Sport", marque:"Benefactor", modele:"Schlagen GT", prix:"$374 000,00" },
    { type:"Sport", marque:"Lampadati", modele:"Corsita", prix:"$380 000,00" },
    { type:"Sport", marque:"Pfister", modele:"Comet", prix:"$390 000,00" },
    { type:"Sport", marque:"Progen", modele:"Itali GTO", prix:"$410 000,00" }
);

// === Super ===
VEHICLES_DATA.push(
    { type:"Super", marque:"Grotti", modele:"Milano", prix:"$145 000,00" },
    { type:"Super", marque:"Benefactor", modele:"Harman", prix:"$154 000,00" },
    { type:"Super", marque:"Pfister", modele:"Dinka", prix:"$190 000,00" },
    { type:"Super", marque:"Dinka", modele:"Nexus RR", prix:"$230 000,00" },
    { type:"Super", marque:"Vapid", modele:"Bullet", prix:"$240 000,00" },
    { type:"Super", marque:"Benefactor", modele:"Schlagen SP", prix:"$280 000,00" },
    { type:"Super", marque:"Obey", modele:"Ten FR", prix:"$285 000,00" },
    { type:"Super", marque:"Bravado", modele:"Banshee 900R", prix:"$290 000,00" },
    { type:"Super", marque:"Empero", modele:"Ronin", prix:"$290 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Vacca", prix:"$290 000,00" },
    { type:"Super", marque:"Progen", modele:"GP1", prix:"$370 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Reaper", prix:"$370 000,00" },
    { type:"Super", marque:"Übermacth", modele:"SC1", prix:"$380 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Torero XO", prix:"$420 000,00" },
    { type:"Super", marque:"Ocelot", modele:"Virtue", prix:"$420 000,00" },
    { type:"Super", marque:"Coil", modele:"Voltic", prix:"$430 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Tempesta", prix:"$524 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Infernus", prix:"$580 000,00" },
    { type:"Super", marque:"Vapid", modele:"FMJ", prix:"$590 000,00" },
    { type:"Super", marque:"Lampadati", modele:"Tigon", prix:"$610 000,00" },
    { type:"Super", marque:"Grotti", modele:"Cheetah", prix:"$640 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Osiris", prix:"$680 000,00" },
    { type:"Super", marque:"Progen", modele:"T20", prix:"$680 000,00" },
    { type:"Super", marque:"Ocelot", modele:"XA-21", prix:"$720 000,00" },
    { type:"Super", marque:"Grotti", modele:"Turismo R", prix:"$780 000,00" },
    { type:"Super", marque:"Överflöd", modele:"Entity XF", prix:"$800 000,00" },
    { type:"Super", marque:"Progen", modele:"Itali GTB Custom", prix:"$830 000,00" },
    { type:"Super", marque:"Truffade", modele:"Thrax", prix:"$890 000,00" },
    { type:"Super", marque:"Överflöd", modele:"Zeno", prix:"$920 000,00" },
    { type:"Super", marque:"Överflöd", modele:"Entity MT", prix:"$940 000,00" },
    { type:"Super", marque:"Grotti", modele:"Turismo Omaggio", prix:"$940 000,00" },
    { type:"Super", marque:"Pfister", modele:"811", prix:"$945 000,00" },
    { type:"Super", marque:"Progen", modele:"Emerus", prix:"$1 040 000,00" },
    { type:"Super", marque:"Benefactor", modele:"Krieger", prix:"$1 080 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Zorrusso", prix:"$1 090 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Tezeract", prix:"$1 170 000,00" },
    { type:"Super", marque:"Cheval", modele:"Taipan", prix:"$1 200 000,00" },
    { type:"Super", marque:"Grotti", modele:"Furia", prix:"$1 280 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Ignus", prix:"$1 540 000,00" },
    { type:"Super", marque:"Överflöd", modele:"Tyrant", prix:"$1 680 000,00" },
    { type:"Super", marque:"Pegassi", modele:"Zentorno", prix:"$1 700 000,00" },
    { type:"Super", marque:"Truffade", modele:"Adder", prix:"$1 800 000,00" }
);

// === Motorcyles ===
VEHICLES_DATA.push(
    { type:"Motorcyles", marque:"Pegassi", modele:"Faggio", prix:"$2 500,00" },
    { type:"Motorcyles", marque:"Pegassi", modele:"Faggio Sport", prix:"$2 900,00" },
    { type:"Motorcyles", marque:"Dinka", modele:"Enduro", prix:"$5 500,00" },
    { type:"Motorcyles", marque:"Maibastu", modele:"Sanchez", prix:"$7 500,00" },
    { type:"Motorcyles", marque:"Maibastu", modele:"Manchez", prix:"$8 300,00" },
    { type:"Motorcyles", marque:"Maibastu", modele:"Sanchez Livery", prix:"$8 500,00" },
    { type:"Motorcyles", marque:"Pegassi", modele:"FCR 1000", prix:"$9 000,00" },
    { type:"Motorcyles", marque:"Pegassi", modele:"Esskey", prix:"$12 000,00" },
    { type:"Motorcyles", marque:"Shitzu", modele:"Vader", prix:"$12 000,00" },
    { type:"Motorcyles", marque:"Western", modele:"Wolfsbane", prix:"$14 000,00" },
    { type:"Motorcyles", marque:"Shitzu", modele:"PCJ-600", prix:"$15 000,00" },
    { type:"Motorcyles", marque:"LCC", modele:"Hexer", prix:"$16 000,00" },
    { type:"Motorcyles", marque:"Pegassi", modele:"FCR 1000 Custom", prix:"$19 000,00" },
    { type:"Motorcyles", marque:"Dinka", modele:"Vindicator", prix:"$19 000,00" },
    { type:"Motorcyles", marque:"Principe", modele:"Nemesis", prix:"$20 000,00" },
    { type:"Motorcyles", marque:"LCC", modele:"Avarus", prix:"$20 000,00" },
    { type:"Motorcyles", marque:"Maibastu", modele:"Super Sanchez", prix:"$20 000,00" },
    { type:"Motorcyles", marque:"Western", modele:"Powersurge", prix:"$21 000,00" },
    { type:"Motorcyles", marque:"Nagasaki", modele:"Chimera", prix:"$21 000,00" },
    { type:"Motorcyles", marque:"WMC", modele:"Bagger", prix:"$22 000,00" },
    { type:"Motorcyles", marque:"Nagasaki", modele:"BF400", prix:"$22 000,00" },
    { type:"Motorcyles", marque:"Dinka", modele:"Thrust", prix:"$22 000,00" },
    { type:"Motorcyles", marque:"Western", modele:"Daemon Custom", prix:"$23 000,00" },
    { type:"Motorcyles", marque:"Principe", modele:"Lectro", prix:"$24 000,00" },
    { type:"Motorcyles", marque:"Western", modele:"Reever", prix:"$25 000,00" },
    { type:"Motorcyles", marque:"Pegassi", modele:"Ruffian", prix:"$25 000,00" },
    { type:"Motorcyles", marque:"LLC", modele:"Innovation", prix:"$26 500,00" },
    { type:"Motorcyles", marque:"Western", modele:"Zombie Chopper", prix:"$27 000,00" },
    { type:"Motorcyles", marque:"Principe", modele:"Diablous", prix:"$27 000,00" },
    { type:"Motorcyles", marque:"Nagasaki", modele:"BF900", prix:"$27 500,00" },
    { type:"Motorcyles", marque:"Shitzu", modele:"Defiler", prix:"$28 000,00" },
    { type:"Motorcyles", marque:"Western", modele:"Zombie Bobber", prix:"$28 000,00" },
    { type:"Motorcyles", marque:"Dinka", modele:"Akuma", prix:"$29 000,00" },
    { type:"Motorcyles", marque:"Pegassi", modele:"Vortex", prix:"$31 000,00" },
    { type:"Motorcyles", marque:"Nagasaki", modele:"Carbon RS", prix:"$32 000,00" },
    { type:"Motorcyles", marque:"WMC", modele:"Nightblade", prix:"$32 000,00" },
    { type:"Motorcyles", marque:"Western", modele:"Gargoyle", prix:"$32 000,00" },
    { type:"Motorcyles", marque:"Nagasaki", modele:"Shinobi", prix:"$34 000,00" },
    { type:"Motorcyles", marque:"Shitzu", modele:"Hakuchou", prix:"$36 000,00" },
    { type:"Motorcyles", marque:"Pegassi", modele:"Bati 801", prix:"$36 000,00" },
    { type:"Motorcyles", marque:"Dinka", modele:"Double-T", prix:"$36 000,00" },
    { type:"Motorcyles", marque:"Principe", modele:"Diablous Custom", prix:"$38 000,00" },
    { type:"Motorcyles", marque:"WMC", modele:"Sovereign", prix:"$39 000,00" },
    { type:"Motorcyles", marque:"Western", modele:"Cliffhanger", prix:"$39 500,00" }
);

// === Off-Roads ===
VEHICLES_DATA.push(
    { type:"Off-Roads", marque:"Annis", modele:"blazer", prix:"$7 500,00" },
    { type:"Off-Roads", marque:"Annis", modele:"blazer Sport", prix:"$9 250,00" },
    { type:"Off-Roads", marque:"Canis", modele:"Kalahari", prix:"$14 000,00" },
    { type:"Off-Roads", marque:"Annis", modele:"BF Injection", prix:"$18 000,00" },
    { type:"Off-Roads", marque:"Canis", modele:"Mesa", prix:"$19 000,00" },
    { type:"Off-Roads", marque:"Vapid", modele:"Rebel", prix:"$20 000,00" },
    { type:"Off-Roads", marque:"Declasse", modele:"Rancher XL", prix:"$24 000,00" },
    { type:"Off-Roads", marque:"Annis", modele:"Hellion", prix:"$27 000,00" },
    { type:"Off-Roads", marque:"Declasse", modele:"Yosemite Rancher", prix:"$32 000,00" },
    { type:"Off-Roads", marque:"Vapid", modele:"Sandking SWB", prix:"$38 000,00" },
    { type:"Off-Roads", marque:"Vapid", modele:"Riata", prix:"$38 000,00" },
    { type:"Off-Roads", marque:"Karin", modele:"Everon", prix:"$44 000,00" },
    { type:"Off-Roads", marque:"Vapid", modele:"Sandking XL", prix:"$45 000,00" },
    { type:"Off-Roads", marque:"Maibatsu", modele:"MonstroCiti", prix:"$48 000,00" },
    { type:"Off-Roads", marque:"Vapid", modele:"Caracara", prix:"$54 000,00" },
    { type:"Off-Roads", marque:"Nagasaki", modele:"Oultaw", prix:"$58 000,00" },
    { type:"Off-Roads", marque:"Bordeaux", modele:"Vivant GRB", prix:"$69 000,00" },
    { type:"Off-Roads", marque:"Bravado", modele:"Bison HF", prix:"$95 000,00" },
    { type:"Off-Roads", marque:"Annis", modele:"Dubsta 6x6", prix:"$260 000,00" }
);

// === VAN ===
VEHICLES_DATA.push(
    { type:"VAN", marque:"Vapid", modele:"Minivan", prix:"$27 000,00" },
    { type:"VAN", marque:"Bravado", modele:"Youga Classic", prix:"$31 000,00" },
    { type:"VAN", marque:"Bravado", modele:"Youga", prix:"$31 000,00" },
    { type:"VAN", marque:"Zirconium", modele:"Journey II", prix:"$32 000,00" },
    { type:"VAN", marque:"Vapid", modele:"Minivan Custom", prix:"$32 000,00" },
    { type:"VAN", marque:"Declasse", modele:"Moonbeam", prix:"$32 000,00" },
    { type:"VAN", marque:"Declasse", modele:"Moonbeam Custom", prix:"$35 000,00" },
    { type:"VAN", marque:"BF", modele:"Surfer Custom", prix:"$36 000,00" },
    { type:"VAN", marque:"Declasse", modele:"Burrito Custom", prix:"$39 000,00" },
    { type:"VAN", marque:"BF", modele:"Surfer", prix:"$40 000,00" },
    { type:"VAN", marque:"Bravado", modele:"Rumpo Custom", prix:"$48 000,00" },
    { type:"VAN", marque:"Bravado", modele:"Esperta", prix:"$55 000,00" },
    { type:"VAN", marque:"Vapid", modele:"Speedo Custom", prix:"$238 000,00" }
);
